// stdafx.h : include file for standard system include files,
// or project specific include files that are used frequently, but
// are changed infrequently
//

#pragma once


#define WIN32_LEAN_AND_MEAN		// Exclude rarely-used stuff from Windows headers




#ifdef WIN32
#include <stdlib.h>
#include <stdio.h>
#include <conio.h>
#include <tchar.h>
#include <string>
#include <map>
#include <vector>
#include <fstream>
#include <time.h>
#include "shlwapi.h"
using namespace std;

#define __getch _getch
#define __kbhit _kbhit


#else
#include "lp_stdlib.h"
#include "lp_stdio.h"
#include "lp_conio.h"
#include "lp_tchar.h"
#endif


//#include <stdio.h>
//#include <stdlib.h>
//#include <conio.h>
//#include <tchar.h>
// stdafx.h : include file for standard system include files,
#define BUFFER_SIZE 512

#define __this__version__ "FoxLite_11.10.20"
#define __this__author__   "dai-xin.gao@foxconn.com"
typedef struct 
{
	double dPathLoss1;
	double dPathLoss2;
	double dPathLoss3;
	double dPathLoss4;
}PATH_LOSS;

typedef struct 
{
	char szSubItem[24];
	char szBandWidth[8];
	char szDataRate[8];
	char szPacketFormat11n[12];
	char szPreamble[8];
	int nFreq;
	double dTargetPower;
	double dEvmSpec;
	int nTx1;
	int nTx2;
	int nTx3;
	int nTx4;
	int nSamplingTime;
	PATH_LOSS g_PathLoss;
}TX_PARAM_IN;

typedef struct 
{
	double dPowerUpper2g;
	double dPowerLower2g;
	double dPowerUpper5g;
	double dPowerLower5g;
	double dMaskPercent;
	double dPerPercent;
	double dPerPercentOFDM;
	double dFreqencyShift;
	double dEvmLower;
}TS_WIFI_LIMIT;

typedef struct 
{
	char szSubItem[24];
	char szBandWidth[8];
	char szDataRate[8];
	char szPacketFormat11n[12];
	char szPreamble[8];
	int nFreq;
	double dRxPowerLevel;
	int nRx1;
	int nRx2;
	int nRx3;
	int nRx4;
	PATH_LOSS g_PathLoss;
}RX_PARAM_IN;


typedef pair<string, TX_PARAM_IN> Tx_Pair;
typedef pair<string, RX_PARAM_IN> Rx_Pair;
typedef vector<string> STRING_TESTITEM_VECTOR;
typedef struct 
{
	char szSubItem[24];
	double EVM_AVG_ALL;
	double EVM_AVG_1;
	double EVM_AVG_2;
	double EVM_AVG_3;
	double EVM_AVG_4;
	double POWER_AVG_ALL;
	double POWER_AVG_1;
	double POWER_AVG_2;
	double POWER_AVG_3;
	double POWER_AVG_4;
	double FREQ_ERROR;
	double MASK_PERCENT;
}TX_PARAM_RETURN;

typedef struct 
{
	double dPerPercent;
	double dRxPowerLevel;
}RX_PARAM_RETURN;
typedef struct
{
	int RunMode;	// = 0
	int RepeatTimes; //= 1
	int ExitWhenDone; //= 0
	int ShowFailInfo; //= 0
	int RetryMode;
	int nRetryTimes;
	int ReloadDutDLL;

	int IQ_TESTER_RECONNECT;
	TCHAR szDUT_DLL_FILENAME[BUFFER_SIZE];
	TCHAR szConnectionString[BUFFER_SIZE];	
	TCHAR szTxPathLossFile[BUFFER_SIZE];
	TCHAR szRxPathLossFile[BUFFER_SIZE];
	TCHAR IQ_TESTER_IP1[BUFFER_SIZE];
	TCHAR IQ_TESTER_IP2[BUFFER_SIZE];
	TCHAR IQ_TESTER_IP3[BUFFER_SIZE];
	TCHAR IQ_TESTER_IP4[BUFFER_SIZE];
	TCHAR PACKET_FORMAT[BUFFER_SIZE];

	// add by daixin to support dual test, 2012-12-10
	int DH_ENABLE; //= 0
	int DH_OBTAIN_CONTROL_TIMEOUT_MS;
	int DH_PROBE_TIME_MS;
	int DH_TOKEN_ID;
	// add end

}TS_TEST_CTRL;

typedef struct 
{
	int ANALYSIS_11AG_AMPL_TRACK ;
	int ANALYSIS_11AG_CH_ESTIMATE ;
	int ANALYSIS_11AG_FREQ_SYNC ;
	int ANALYSIS_11AG_PH_CORR_MODE ;
	int ANALYSIS_11AG_SYM_TIM_CORR ;
	int ANALYSIS_11B_DC_REMOVE_FLAG ;
	int ANALYSIS_11B_EQ_TAPS ;
	int ANALYSIS_11B_FIXED_01_DATA_SEQUENCE ;
	int ANALYSIS_11B_METHOD_11B ;
	int ANALYSIS_11N_AMPLITUDE_TRACKING ;
	int ANALYSIS_11N_DECODE_PSDU ;
	int ANALYSIS_11N_FREQUENCY_CORRELATION ;
	int ANALYSIS_11N_FULL_PACKET_CHANNEL_EST ;
	int ANALYSIS_11N_PHASE_CORR ;
	int ANALYSIS_11N_SYM_TIMING_CORR ;
	int DUT_KEEP_TRANSMIT ;
	int DUT_RX_SETTLE_TIME_MS ;
	int DUT_TX_SETTLE_TIME_MS ;

	// The following 5 parametes are removed because of the new IQLiteCore_3.0.1
	int EVM_11AG_SAMPLE_INTERVAL_US ;
	int EVM_11B_L_SAMPLE_INTERVAL_US ;
	int EVM_11B_S_SAMPLE_INTERVAL_US ;
	int EVM_11N_GREENFIELD_SAMPLE_INTERVAL_US ;
	int EVM_11N_MIXED_SAMPLE_INTERVAL_US ;

	int EVM_AVERAGE ;
	int EVM_SYMBOL_NUM ;
	int IQ2010_EXT_ENABLE ;
	int IQ_P_TO_A_11AG_12M ;
	int IQ_P_TO_A_11AG_18M ;
	int IQ_P_TO_A_11AG_24M ;
	int IQ_P_TO_A_11AG_36M ;
	int IQ_P_TO_A_11AG_48M ;
	int IQ_P_TO_A_11AG_54M ;
	int IQ_P_TO_A_11AG_6M ;
	int IQ_P_TO_A_11AG_9M ;
	int IQ_P_TO_A_11B_11M ;
	int IQ_P_TO_A_11B_1M ;
	int IQ_P_TO_A_11B_2M ;
	int IQ_P_TO_A_11B_5_5M ;
	int IQ_P_TO_A_11B_CH14 ;
	int IQ_P_TO_A_11N_MCS0 ;
	int IQ_P_TO_A_11N_MCS1 ;
	int IQ_P_TO_A_11N_MCS2 ;
	int IQ_P_TO_A_11N_MCS3 ;
	int IQ_P_TO_A_11N_MCS4 ;
	int IQ_P_TO_A_11N_MCS5 ;
	int IQ_P_TO_A_11N_MCS6 ;
	int IQ_P_TO_A_11N_MCS7 ;
	int MASK_DSSS_SAMPLE_INTERVAL_US ;
	int MASK_OFDM_SAMPLE_INTERVAL_US ;
	int PER_11AG_12_PACKETS_NUM ;
	int PER_11AG_18_PACKETS_NUM ;
	int PER_11AG_24_PACKETS_NUM ;
	int PER_11AG_36_PACKETS_NUM ;
	int PER_11AG_48_PACKETS_NUM ;
	int PER_11AG_54_PACKETS_NUM ;
	int PER_11AG_6_PACKETS_NUM ;
	int PER_11AG_9_PACKETS_NUM ;
	int PER_11B_11_PACKETS_NUM ;
	int PER_11B_1_PACKETS_NUM ;
	int PER_11B_2_PACKETS_NUM ;
	int PER_11B_5_5_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS0_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS10_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS11_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS12_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS13_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS14_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS15_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS16_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS17_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS18_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS19_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS1_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS20_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS21_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS22_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS23_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS24_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS25_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS26_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS27_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS28_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS29_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS2_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS30_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS31_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS3_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS4_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS5_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS6_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS7_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS8_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_MCS9_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS0_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS10_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS11_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS12_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS13_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS14_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS15_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS16_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS17_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS18_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS19_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS1_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS20_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS21_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS22_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS23_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS24_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS25_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS26_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS27_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS28_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS29_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS2_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS30_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS31_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS3_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS4_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS5_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS6_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS7_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS8_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_MCS9_PACKETS_NUM ;
	int PER_VSG_TIMEOUT_SEC ;
	int PM_AVERAGE ;
	int PM_DSSS_SAMPLE_INTERVAL_US ;
	int PM_IF_FREQ_SHIFT_MHZ ;
	int PM_OFDM_SAMPLE_INTERVAL_US ;
	int SPECTRUM_DSSS_SAMPLE_INTERVAL_US ;
	int SPECTRUM_OFDM_SAMPLE_INTERVAL_US ;
	int VSA_PORT ;
	int VSA_SAVE_CAPTURE_ALWAYS ;
	int VSA_SAVE_CAPTURE_ON_FAILED ;
	int VSA_SKIP_PACKET_COUNT ;
	int VSA_TRIGGER_TIMEOUT_SEC ;
	int VSA_TRIGGER_TYPE ;
	int VSG_PORT ;

	// new add for IQLite_Core_3.0.1
	// type: integer
	int AUTO_GAIN_CONTROL_ENABLE ;
	int AUTO_READING_LIMIT ;
	int EVM_CAPTURE_TIME_11AG_US ;
	int EVM_CAPTURE_TIME_11B_L_US ;
	int EVM_CAPTURE_TIME_11B_S_US ;
	int EVM_CAPTURE_TIME_11N_GREENFIELD_US ;
	int EVM_CAPTURE_TIME_11N_MIXED_US ;
	int EVM_CAPTURE_TIME_11P_HALF_US ;
	int EVM_CAPTURE_TIME_11P_QUAR_US ;
	int MASK_FFT_AVERAGE ;
	int MASK_HALF_SAMPLE_INTERVAL_US ;
	int MASK_QUAR_SAMPLE_INTERVAL_US ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS0_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS10_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS11_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS12_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS13_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS14_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS15_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS16_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS17_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS18_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS19_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS1_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS20_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS21_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS22_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS23_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS24_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS25_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS26_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS27_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS28_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS29_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS2_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS30_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS31_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS3_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS4_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS5_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS6_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS7_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS8_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_L_GI_MCS9_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS0_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS10_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS11_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS12_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS13_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS14_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS15_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS16_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS17_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS18_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS19_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS1_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS20_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS21_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS22_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS23_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS24_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS25_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS26_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS27_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS28_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS29_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS2_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS30_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS31_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS3_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS4_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS5_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS6_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS7_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS8_PACKETS_NUM ;
	int PER_11N_HT20_GREENFIELD_S_GI_MCS9_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS0_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS10_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS11_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS12_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS13_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS14_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS15_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS16_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS17_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS18_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS19_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS1_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS20_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS21_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS22_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS23_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS24_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS25_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS26_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS27_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS28_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS29_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS2_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS30_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS31_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS3_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS4_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS5_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS6_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS7_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS8_PACKETS_NUM ;
	int PER_11N_HT20_MIXED_S_GI_MCS9_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS0_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS10_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS11_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS12_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS13_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS14_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS15_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS16_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS17_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS18_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS19_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS1_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS20_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS21_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS22_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS23_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS24_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS25_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS26_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS27_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS28_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS29_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS2_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS30_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS31_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS3_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS4_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS5_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS6_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS7_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS8_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_L_GI_MCS9_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS0_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS10_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS11_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS12_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS13_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS14_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS15_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS16_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS17_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS18_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS19_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS1_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS20_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS21_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS22_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS23_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS24_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS25_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS26_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS27_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS28_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS29_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS2_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS30_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS31_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS3_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS4_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS5_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS6_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS7_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS8_PACKETS_NUM ;
	int PER_11N_HT40_GREENFIELD_S_GI_MCS9_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS0_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS10_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS11_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS12_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS13_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS14_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS15_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS16_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS17_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS18_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS19_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS1_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS20_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS21_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS22_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS23_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS24_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS25_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS26_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS27_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS28_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS29_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS2_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS30_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS31_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS3_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS4_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS5_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS6_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS7_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS8_PACKETS_NUM ;
	int PER_11N_HT40_MIXED_S_GI_MCS9_PACKETS_NUM ;
	int PER_11P_HALF12_PACKETS_NUM ;
	int PER_11P_HALF18_PACKETS_NUM ;
	int PER_11P_HALF24_PACKETS_NUM ;
	int PER_11P_HALF27_PACKETS_NUM ;
	int PER_11P_HALF3_PACKETS_NUM ;
	int PER_11P_HALF4_5_PACKETS_NUM ;
	int PER_11P_HALF6_PACKETS_NUM ;
	int PER_11P_HALF9_PACKETS_NUM ;
	int PER_11P_QUAR12_PACKETS_NUM ;
	int PER_11P_QUAR13_5_PACKETS_NUM ;
	int PER_11P_QUAR1_5_PACKETS_NUM ;
	int PER_11P_QUAR2_25_PACKETS_NUM ;
	int PER_11P_QUAR3_PACKETS_NUM ;
	int PER_11P_QUAR4_5_PACKETS_NUM ;
	int PER_11P_QUAR6_PACKETS_NUM ;
	int PER_11P_QUAR9_PACKETS_NUM ;
	int PM_HALF_SAMPLE_INTERVAL_US ;
	int PM_QUAR_SAMPLE_INTERVAL_US ;
	int RELATIVE_LIMIT ;
	int RESET_TEST_ITEM_DURING_RETRY ;
	int RETRY_ERROR_ITEMS ;
	int RETRY_TEST_ITEM ;
	int SPECTRUM_HALF_SAMPLE_INTERVAL_US ;
	int SPECTRUM_QUAR_SAMPLE_INTERVAL_US ;

	// type; String
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS10_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS11_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS12_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS13_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS14_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS15_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS16_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS17_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS18_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS19_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS20_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS21_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS22_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS23_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS24_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS25_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS26_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS27_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS28_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS29_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS30_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS31_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS8_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_L_GI_MCS9_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS10_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS11_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS12_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS13_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS14_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS15_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS16_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS17_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS18_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS19_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS20_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS21_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS22_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS23_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS24_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS25_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS26_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS27_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS28_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS29_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS30_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS31_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS8_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_S_GI_MCS9_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS24_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS25_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS26_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS27_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS28_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS29_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS30_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS31_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS10_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS11_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS12_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS13_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS14_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS15_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS16_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS17_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS18_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS19_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS20_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS21_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS22_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS23_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS24_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS25_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS26_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS27_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS28_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS29_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS30_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS31_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS8_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_S_GI_MCS9_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS10_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS11_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS12_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS13_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS14_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS15_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS16_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS17_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS18_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS19_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS20_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS21_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS22_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS23_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS24_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS25_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS26_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS27_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS28_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS29_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS30_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS31_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS8_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_L_GI_MCS9_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS10_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS11_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS12_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS13_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS14_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS15_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS16_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS17_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS18_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS19_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS20_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS21_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS22_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS23_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS24_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS25_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS26_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS27_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS28_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS29_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS30_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS31_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS8_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_S_GI_MCS9_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS24_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS25_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS26_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS27_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS28_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS29_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS30_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS31_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS10_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS11_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS12_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS13_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS14_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS15_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS16_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS17_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS18_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS19_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS20_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS21_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS22_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS23_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS24_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS25_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS26_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS27_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS28_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS29_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS30_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS31_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS8_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_S_GI_MCS9_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS0_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS10_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS11_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS12_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS13_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS14_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS15_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS16_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS17_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS18_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS19_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS1_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS20_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS21_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS22_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS23_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS24_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS25_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS26_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS27_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS28_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS29_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS2_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS30_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS31_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS3_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS4_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS5_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS6_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS7_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS8_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_L_GI_MCS9_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS0_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS10_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS11_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS12_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS13_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS14_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS15_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS16_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS17_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS18_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS19_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS1_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS20_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS21_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS22_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS23_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS24_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS25_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS26_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS27_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS28_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS29_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS2_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS30_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS31_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS3_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS4_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS5_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS6_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS7_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS8_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_GREENFIELD_S_GI_MCS9_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS0_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS10_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS11_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS12_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS13_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS14_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS15_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS16_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS17_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS18_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS19_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS1_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS20_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS21_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS22_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS23_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS24_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS25_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS26_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS27_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS28_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS29_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS2_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS30_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS31_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS3_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS4_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS5_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS6_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS7_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS8_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_S_GI_MCS9_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS0_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS10_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS11_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS12_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS13_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS14_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS15_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS16_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS17_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS18_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS19_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS1_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS20_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS21_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS22_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS23_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS24_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS25_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS26_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS27_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS28_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS29_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS2_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS30_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS31_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS3_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS4_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS5_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS6_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS7_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS8_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_L_GI_MCS9_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS0_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS10_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS11_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS12_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS13_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS14_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS15_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS16_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS17_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS18_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS19_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS1_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS20_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS21_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS22_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS23_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS24_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS25_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS26_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS27_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS28_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS29_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS2_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS30_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS31_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS3_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS4_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS5_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS6_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS7_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS8_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_GREENFIELD_S_GI_MCS9_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS0_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS10_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS11_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS12_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS13_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS14_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS15_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS16_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS17_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS18_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS19_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS1_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS20_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS21_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS22_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS23_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS24_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS25_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS26_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS27_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS28_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS29_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS2_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS30_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS31_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS3_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS4_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS5_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS6_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS7_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS8_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_S_GI_MCS9_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11P_HALF12_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11P_HALF18_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11P_HALF24_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11P_HALF27_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11P_HALF3_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11P_HALF4_5_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11P_HALF6_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11P_HALF9_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11P_QUAR12_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11P_QUAR13_5_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11P_QUAR1_5_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11P_QUAR2_25_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11P_QUAR3_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11P_QUAR4_5_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11P_QUAR6_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11P_QUAR9_WAVEFORM_NAME [BUFFER_SIZE];
	// new add end
	double VSA_ACK_POWER_RMS_DBM ;
	double VSA_ACK_TRIGGER_LEVEL_DBM ;
	double VSA_AMPLITUDE_TOLERANCE_DB ;
	double VSA_PRE_TRIGGER_TIME_US ;
	double VSA_TRIGGER_LEVEL_DB ;
	double VSG_MAX_POWER_11B ;
	double VSG_MAX_POWER_11G ;
	double VSG_MAX_POWER_11N ;
	TCHAR EVM_11N_HT20_MIXED_MCS10_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS11_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS12_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS13_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS14_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS15_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS16_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS17_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS18_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS19_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS20_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS21_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS22_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS23_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS8_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_MIXED_MCS9_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS10_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS11_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS12_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS13_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS14_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS15_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS16_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS17_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS18_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS19_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS20_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS21_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS22_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS23_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS8_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_MIXED_MCS9_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_MCS10_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_MCS11_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_MCS12_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_MCS13_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_MCS14_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_MCS15_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_MCS16_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_MCS17_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_MCS18_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_MCS19_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_MCS20_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_MCS21_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_MCS22_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_MCS23_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT20_GREENFIELD_MCS8_REFERENCE_FILE_NAME [BUFFER_SIZE]; 
	TCHAR EVM_11N_HT20_GREENFIELD_MCS9_REFERENCE_FILE_NAME [BUFFER_SIZE]; 
	TCHAR EVM_11N_HT40_GREENFIELD_MCS10_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_MCS11_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_MCS12_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_MCS13_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_MCS14_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_MCS15_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_MCS16_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_MCS17_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_MCS18_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_MCS19_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_MCS20_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_MCS21_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_MCS22_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_MCS23_REFERENCE_FILE_NAME [BUFFER_SIZE];
	TCHAR EVM_11N_HT40_GREENFIELD_MCS8_REFERENCE_FILE_NAME [BUFFER_SIZE]; 
	TCHAR EVM_11N_HT40_GREENFIELD_MCS9_REFERENCE_FILE_NAME [BUFFER_SIZE]; 
	TCHAR PER_11AG_12_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11AG_18_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11AG_24_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11AG_36_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11AG_48_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11AG_54_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11AG_6_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11AG_9_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11B_11L_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11B_11S_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11B_1_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11B_2L_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11B_2S_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11B_5_5L_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11B_5_5S_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS0_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS10_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS11_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS12_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS13_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS14_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS15_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS16_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS17_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS18_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS19_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS1_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS20_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS21_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS22_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS23_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS24_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS25_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS26_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS27_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS28_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS29_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS2_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS30_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS31_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS3_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS4_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS5_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS6_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS7_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS8_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT20_MIXED_MCS9_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS0_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS10_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS11_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS12_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS13_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS14_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS15_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS16_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS17_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS18_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS19_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS1_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS20_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS21_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS22_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS23_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS24_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS25_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS26_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS27_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS28_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS29_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS2_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS30_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS31_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS3_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS4_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS5_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS6_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS7_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS8_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_11N_HT40_MIXED_MCS9_WAVEFORM_NAME [BUFFER_SIZE];
	TCHAR PER_WAVEFORM_DESTINATION_MAC [BUFFER_SIZE];
	TCHAR PER_WAVEFORM_PATH [BUFFER_SIZE];

	TS_TEST_CTRL TestCtrl;
	TS_WIFI_LIMIT WifiLimit;
}TS_Global_Setting;

enum err_prepare
{
	err_RegisterTechnologyDll=90,
	err_GLOBAL_SETTINGS,
	err_LOAD_PATH_LOSS_TABLE,
	err_CONNECT_IQ_TESTER,
	err_INSERT_DUT,
	err_INITIALIZE_DUT
};
// Step 1: Register the WiFi Test functions with TestManager
//         So that all WiFi Test functions will be made available to Test Manager
void run_RegisterTechnologyDll(void);

// Step 2: Setup the global settings
//         Global settings are used by all test functions
//         They do not belong to any specific test function
void run_GLOBAL_SETTINGS(void);

// Step 3: Load path loss table from file
void run_LOAD_PATH_LOSS_TABLE(void);

// Step 4: Connect IQTester (IP address needed)
void run_CONNECT_IQ_TESTER(_TCHAR* ipAddress);

// Step 5: Insert DUT for test
void run_INSERT_DUT(void);

// Step 6: Initial DUT for test
void run_INITIALIZE_DUT(void);

// Step 7: TX Verify EVM Test     
void run_TX_VERIFY_EVM(TX_PARAM_IN *txParam, TX_PARAM_RETURN *txReturn);

// Step 8: TX Verify Power Test     
void run_TX_VERIFY_POWER(TX_PARAM_IN *txParam, TX_PARAM_RETURN *txReturn);

// Step 9: TX Verify Mask Test     
void run_TX_VERIFY_MASK(TX_PARAM_IN *txParam, TX_PARAM_RETURN *txReturn);

// Step 10: TX Verify Spectrum Test     
void run_TX_VERIFY_SPECTRUM(void);

// Step 11: RX Verify PER Test   
void run_RX_VERIFY_PER(RX_PARAM_IN *rxParam, RX_PARAM_RETURN *rxReturn);   

// Step 12: Remove DUT
void run_REMOVE_DUT(void);

// Step 13: Disconnect IQTester
void run_DISCONNECT_IQ_TESTER(void); 
#if 0
// Step 1: Register the WiFi Test functions with TestManager
//         So that all WiFi Test functions will be made available to Test Manager
void run_RegisterTechnologyDll(void);

// Step 2: Setup the global settings
//         Global settings are used by all test functions
//         They do not belong to any specific test function
void run_GLOBAL_SETTINGS(void);

// Step 3: Load path loss table from file
void run_LOAD_PATH_LOSS_TABLE(void);

// Step 4: Connect IQTester (IP address needed)
void run_CONNECT_IQ_TESTER(_TCHAR* ipAddress);

// Step 5: Insert DUT for test
void run_INSERT_DUT(void);

// Step 6: Initial DUT for test
void run_INITIALIZE_DUT(void);

// Step 7: TX Verify EVM Test     
void run_TX_VERIFY_EVM(void);

// Step 8: TX Verify Power Test     
void run_TX_VERIFY_POWER(void);

// Step 9: TX Verify Mask Test     
void run_TX_VERIFY_MASK(void);

// Step 10: TX Verify Spectrum Test     
void run_TX_VERIFY_SPECTRUM(void);

// Step 11: RX Verify PER Test   
void run_RX_VERIFY_PER(void);   

// Step 12: Remove DUT
void run_REMOVE_DUT(void);

// Step 13: Disconnect IQTester
void run_DISCONNECT_IQ_TESTER(void); 


#endif